server:
  port: 80

#服务别名----注册zookeeper到注册中心名称
spring:
  application:
    name: consumer-service
  cloud:
    zookeeper:
      connect-string: 0.0.0.0:2181
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment?serverTimezone=CTT&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456