server:
  port: 80

spring:
  application:
    name: consumer-serivce
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment?serverTimezone=CTT&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #      设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      #       defaultZone: http://localhost:7001/eureka #单机版
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka  #集群版
  instance:
    instance-id: consumer80
    prefer-ip-address: true  #访问路径可以显示IP地址

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.service.common.entity.Payment