server:
  port: 80

#服务别名----注册consul到注册中心名称
spring:
  application:
    name: consumer-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment?serverTimezone=CTT&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456